-- ============================================================
-- ABHINANDAN PORTFOLIO / SUPABASE DOCUMENT ROOM
-- ============================================================
-- Run this entire file in the Supabase SQL Editor.
-- Safe to re-run on the current/older portfolio schema.
--
-- Document access modes:
--   preview  = guests can preview only
--   download = guests can download only
--   private  = admins only; hidden from guest document room
--
-- IMPORTANT:
-- The documents Storage bucket remains PRIVATE.
-- Guest access uses short-lived signed URLs generated by the
-- browser through Supabase RLS. No service-role/secret key is
-- ever sent to the browser.

create extension if not exists pgcrypto;

-- ============================================================
-- PROFILES
-- ============================================================

create table if not exists public.profiles(
    id uuid primary key references auth.users(id) on delete cascade,
    display_name text not null default '',
    role text not null default 'admin' check(role='admin'),
    status text not null default 'pending'
        check(status in('pending','approved','disabled')),
    created_at timestamptz not null default now()
);

-- ============================================================
-- DOCUMENTS
-- ============================================================

create table if not exists public.documents(
    id uuid primary key default gen_random_uuid(),
    title text not null,
    type text not null,
    storage_path text not null unique,
    download_allowed boolean not null default false,
    access_mode text not null default 'preview',
    created_by uuid not null references public.profiles(id),
    created_at timestamptz not null default now()
);

-- Older installations may not have these columns.
alter table public.documents
    add column if not exists download_allowed boolean not null default false;

alter table public.documents
    add column if not exists access_mode text;

-- Migrate old records exactly once from the old boolean setting.
update public.documents
set access_mode = case
    when download_allowed = true then 'download'
    else 'preview'
end
where access_mode is null
   or access_mode not in ('preview','download','private');

alter table public.documents
    alter column access_mode set default 'preview';

alter table public.documents
    alter column access_mode set not null;

alter table public.documents drop constraint if exists documents_type_check;
alter table public.documents add constraint documents_type_check
check(type in('cv','report','certificate','academic','project','other'));

alter table public.documents drop constraint if exists documents_access_mode_check;
alter table public.documents add constraint documents_access_mode_check
check(access_mode in('preview','download','private'));

-- Keep the legacy column synchronized for compatibility with any
-- older copies of the admin page. New code uses access_mode.
update public.documents
set download_allowed = (access_mode = 'download');

-- ============================================================
-- ADMIN CHECK
-- ============================================================

create or replace function public.is_approved_admin()
returns boolean
language sql
stable
security definer
set search_path=public
as $$
    select exists(
        select 1
        from public.profiles
        where id=auth.uid()
          and role='admin'
          and status='approved'
    );
$$;

-- ============================================================
-- AUTOMATIC PROFILE AFTER SIGNUP
-- ============================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
    insert into public.profiles(id, display_name, role, status)
    values(
        new.id,
        coalesce(new.raw_user_meta_data->>'display_name',''),
        'admin',
        'pending'
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- ============================================================
-- RLS
-- ============================================================

alter table public.profiles enable row level security;
alter table public.documents enable row level security;

-- Remove previous versions before recreating them.
drop policy if exists "profile read" on public.profiles;
drop policy if exists "admin update profiles" on public.profiles;
drop policy if exists "admin read docs" on public.documents;
drop policy if exists "public read docs" on public.documents;
drop policy if exists "admin insert docs" on public.documents;
drop policy if exists "admin update docs" on public.documents;
drop policy if exists "admin delete docs" on public.documents;
drop policy if exists "admin upload" on storage.objects;
drop policy if exists "admin storage read" on storage.objects;
drop policy if exists "public document storage read" on storage.objects;
drop policy if exists "admin storage delete" on storage.objects;

create policy "profile read"
on public.profiles for select
using(id=auth.uid() or public.is_approved_admin());

create policy "admin update profiles"
on public.profiles for update
using(public.is_approved_admin())
with check(public.is_approved_admin());

-- Approved admins can see every document, including private ones.
create policy "admin read docs"
on public.documents for select
using(public.is_approved_admin());

-- Guests can see only documents explicitly published as preview/download.
create policy "public read docs"
on public.documents for select
using(access_mode in('preview','download'));

create policy "admin insert docs"
on public.documents for insert
with check(public.is_approved_admin() and created_by=auth.uid());

create policy "admin update docs"
on public.documents for update
using(public.is_approved_admin())
with check(public.is_approved_admin());

create policy "admin delete docs"
on public.documents for delete
using(public.is_approved_admin());

-- ============================================================
-- PRIVATE STORAGE BUCKET
-- ============================================================

insert into storage.buckets(id,name,public)
values('documents','documents',false)
on conflict(id) do update set public=false;

-- Only approved admins may upload.
create policy "admin upload"
on storage.objects for insert
with check(
    bucket_id='documents'
    and public.is_approved_admin()
);

-- Admins can read every stored object.
create policy "admin storage read"
on storage.objects for select
using(
    bucket_id='documents'
    and public.is_approved_admin()
);

-- Guests may request signed URLs only for published documents.
-- Private documents never satisfy this policy.
create policy "public document storage read"
on storage.objects for select
using(
    bucket_id='documents'
    and exists(
        select 1
        from public.documents d
        where d.storage_path = name
          and d.access_mode in('preview','download')
    )
);

create policy "admin storage delete"
on storage.objects for delete
using(
    bucket_id='documents'
    and public.is_approved_admin()
);

-- ============================================================
-- FIRST ADMIN BOOTSTRAP
-- ============================================================
-- 1. Sign up once at /admin/signup.html.
-- 2. Confirm the email if Supabase email confirmation is enabled.
-- 3. Find the user's UUID in Authentication > Users.
-- 4. Run:
--
-- UPDATE public.profiles
-- SET status='approved'
-- WHERE id='AUTH_USER_UUID';
--
-- After approval, the admin dashboard can upload, change access,
-- preview/download private documents, and delete documents.
